### ISSUE TITLE
Windows AMD64 version 1.0.5 doesn't run

### ISSUE THREAD

**Issue by Amitoth** [mmpx12/twitter-media-downloader#11]
Apologies for the terrible title but I have no idea how specific I can be. 

I downloaded the [twitter-media-downloader-v1.0.5-windows-amd64.zip] from the repository. Extracted the .exe file and double clicked on it but nothing happens. 

My processor is an AMD R5 5600H so this is the correct version, I think.

Do I require any pre-requisites or is there an installation method?

**Comment by mmpx12** [comment]
@Amitoth  This a cli app. Double click on it will not work, you have to run it inside a terminal.

The gui app is not yet in the release, you'll have to build it yourself or wait the new release.
