### ISSUE TITLE
Quantify tweet limit mentioned in readme

### ISSUE THREAD

**Issue by 06000208** [mmpx12/twitter-media-downloader#12]
The readme mentions that you will not be able to download more than 3200 tweets.

Is this a total limit and you'll be cut off by twitter after that many tweets somehow, or is it a limit for the User Downloads/bulk tweets features, where it can't get more than 3200 tweets~ at a time?

What does this limit mean for attempting to archive, for example, accounts with 4,000+ tweets?

**Comment by mmpx12** [comment]
This is the limit of the front-end api of twitter.  See  https://github.com/n0madic/twitter-scraper for more info.

If you want more tweet you'll have to use official api or use filter (not yet implemented in this tool) **from:username until:date** (see this issue: https://github.com/n0madic/twitter-scraper/issues/15)

**Comment by 06000208** [comment]
Thanks, hope you have a good day.
