### ISSUE TITLE
rate limit?

### ISSUE THREAD

**Issue by rept36** [mmpx12/twitter-media-downloader#14]
response status 429 Too Many Requests: {"code":88,"message":"Rate limit exceeded."}

**Comment by mmpx12** [comment]
@rept36  Did you scrappe multiple accounts before the error or did it happened on the first one ?

**Comment by mmpx12** [comment]
Lower the number of threads and use proxy or vpn if you are downloading multiple username in short period of time

**Comment by kangxin** [comment]
I'm encountering the same issue. Could you provide specific instructions on how to reduce the number of threads? I've tried running the command every 10 minutes, but I still frequently receive the "response status 429: Too Many Requests - Rate limit exceeded" error message. Do you have any potential solutions for this?
