### ISSUE TITLE
not downloading all media

### ISSUE THREAD

**Issue by kwekewk** [mmpx12/twitter-media-downloader#16]
In some accounts, sometimes only half of the total media is downloaded, even though the -U flag is used.

Is it possible to use a file to input a list of user names?

**Comment by mmpx12** [comment]
@kwekewk  Can you provide a link of tweets that is not downloaded ? (note that gif aren't supported)

Input of usernames will not be implemented since you will hit rate limit.

**Comment by kwekewk** [comment]
This is the total amount of image and video scrapped, then stop after certain(half?) amount.  
3 directories, 212 files
img 169 items 
video 43 items

Reference from the Chrome extension to get only the image of the media (png and jpg)
Target URL : https://twitter.com/Marse_6/media
[Complete] 1294978126766682112 - 1621906663153500167  ( Tweet: 271 / Media: 394 )

**Comment by mmpx12** [comment]
I think its a limitation of twitter-scrapper lib. It can only get 3200 tweets (looks like is now only around 800) (tweet and retweet without media are also count).

Im closing the issue since there is nothing i can do. Maybe open an issue in https://github.com/n0madic/twitter-scraper repo
