### ISSUE TITLE
Download 300 tweets from @user

### ISSUE THREAD

**Issue by Villelmo** [mmpx12/twitter-media-downloader#17]
Execute the following command:

> /twmd -u user -o ~/Desktop/ -a -n 30000

But only download five photo 

**What happen?**

**Comment by mmpx12** [comment]
What is the username of the profile?
Limit seems to be around 600/700 tweets now, and no more 3000.
Also (writen in the readme):

> If the tweet doesn't contain a photo or video nothing will be downloaded but it will count towards the 300.

**Comment by Villelmo** [comment]
> What is the username of the profile? Limit seems to be around 600/700 tweets now, and no more 3000 (i also update twiterscrapper, you should have a little bit more tweets now). Also (writen in the readme):

[@Reuters](https://twitter.com/Reuters)

**Comment by mmpx12** [comment]
@Villelmo which version of twmd are you using? 

With version 1.0.6 and 1.0.8 i have around 600 pics and 60 videos. 

```
twmd -u Reuters -o media -a -n 3000
```

If this command with the latest version (1.0.8), only give you 5 pictures, check if you have enough disk space, or if you massed download before @Reuteurs, you might be block for a while, and in this case try from a different ip or with a proxy.

**Comment by Villelmo** [comment]
version: 1.0.6

**Comment by mmpx12** [comment]
i'm not able to reproduce your issue. Can you provide a dockerfile in which you reproduce the issue?

**Comment by Villelmo** [comment]
Where is the dockerfile?.

**Comment by mmpx12** [comment]
Dockerfile
```Dockerfile
FROM archlinux:latest
RUN pacman -Syu --noconfirm wget
RUN wget "https://github.com/mmpx12/twitter-media-downloader/releases/download/v1.0.8/twitter-media-downloader-v1.0.8-linux-amd64.tar.gz" && \
    tar xvf twitter-media-downloader-v1.0.8-linux-amd64.tar.gz && \
    mv twitter-media-downloader twmd && \
    chmod +x twmd
```

then run:
```sh
docker build -t twmd .
mkdir media || : 
docker run --rm -v ./media:/media twmd ./twmd -u Reuters -o media -a -n 300
```
