### ISSUE TITLE
Seems to have stopped with videos 

### ISSUE THREAD

**Issue by waswosi** [mmpx12/twitter-media-downloader#19]
Could you update please?

**Comment by mmpx12** [comment]
@waswosi  Send tweet link of the video please. I noticed some nsfw videos send error that tweet not exist. Actually there is nothing i can do... Maybe open an issue in twitter-scrapper repo.

**Comment by waswosi** [comment]
For example:
[https://twitter.com/Quinten69109304/status/1675852509515067392](url)
When I press MP4 under the tweet I get "Failed to get tweet information!"

JPG still works.
