### ISSUE TITLE
Add quality

### ISSUE THREAD

**Issue by X7md** [mmpx12/twitter-media-downloader#2]
Can you add option for quality media download?

**Comment by X7md** [comment]
Or option to get all url...

So can easily do that manually

**Comment by mmpx12** [comment]
@X7md Second option is easy to do and will add it tomorrow or saturday.
However for the first one, i don't know how to choose the quality. Any idea how to do it ?

**Comment by mmpx12** [comment]
@X7md yt-dlp is using the twitter api. You can check it with tcpdump:

```sh
# in one terminal
sudo tcpdump -vvvv host api.twitter.com

# in a second terminal
yt-dlp -F 'https://twitter.com/....
```
Since this tool is supposed to be apiless i will not implement it (or maybe later but not soon).

But i add **-z|--url** flag. SO now you can do something like:

```sh
while IFS= read -r url; do
  yt-dlp -f b "$url" 2>/dev/null
done < <(twmd -u Jeddahseasonsa  -v -B --url)
```

**Comment by X7md** [comment]
Thanks a lot 🖤.

**Comment by CXwudi** [comment]
Hi, sorry for bothering on a closed issue, but I guess what X7md wants to say is for example:
Let's say I want to download https://twitter.com/Lunar_815/status/1568316996491821057
twmd would download an image with url https://pbs.twimg.com/media/FcPHriXagAAIfyM.jpg which gives have `1200*1028` resolution, 
but the same image would have a `1772*1588` resolution if I just simply right-click the image and open it in new tab in browser. The url is shown as https://pbs.twimg.com/media/FcPHriXagAAIfyM?format=jpg&name=large

**Comment by CXwudi** [comment]
Actually, the parameter `?format=jpg&name=orig` sounds like is sufficient to get the largest possible resolution. I got this parameter from RSSHub

**Comment by mmpx12** [comment]
@CXwudi Thx a lot for this !! Any idea for videos ?

**Comment by CXwudi** [comment]
@mmpx12 do you have an example of video that is post recently, I want to see what RSSHub is using for video link

**Comment by CXwudi** [comment]
Actually, I have no idea about the video, RSSHub seems to retrieve the similar URL for video as this tool. Only difference is that it has `?tag=12` behind it, but I don't see any difference with or without that parameter

**Comment by mmpx12** [comment]
@CXwudi ok,  i check with yt-dlt and its already downloading the best quality. I also note that not all pictures are  jpg so adding `?name=orig` is enough.

**Comment by CXwudi** [comment]
@mmpx12 unfortunately without `format=jpg` it won't work, but does adding `format=jpg` force all images to be JPG? I don't have an example where an image is not JPG

**Comment by mmpx12** [comment]
@CXwudi Its working for me. Do you have any url where it's not working?

```sh
$ wget -O normal.jpg "https://pbs.twimg.com/media/FcPHriXagAAIfyM.jpg"
$ wget -O large.jpg "https://pbs.twimg.com/media/FcPHriXagAAIfyM.jpg?name=orig"
ls -alh large.jpg normal.jpg 
.rw-r--r--  486 KB  large.jpg
.rw-r--r--  239 KB normal.jpg
```
But adding `format=jpg` don't work with png file (404): https://pbs.twimg.com/media/AirUFB4CAAAvY4B.png?format=jpg&name=orig . If some file aren't working without format i will parse the format from the url, but for now its working

**Comment by CXwudi** [comment]
I modified your PNG example with https://pbs.twimg.com/media/AirUFB4CAAAvY4B?format=png&name=orig, and it works.

I also realized you put the extension `.jpg` right after the `FcPHriXagAAIfyM`, just like https://pbs.twimg.com/media/FcPHriXagAAIfyM.jpg?name=orig. Maybe `format` is only needed if you don't put the extension like https://pbs.twimg.com/media/FcPHriXagAAIfyM?format=jpg&name=large.

**Comment by mmpx12** [comment]
The library is used (https://github.com/n0madic/twitter-scraper) always put extension in url.
Also you can used `name=orig` or `name=small` it will always be  478x635 and a png file.

```sh
$  wget -O orig.jpg "https://pbs.twimg.com/media/AirUFB4CAAAvY4B?format=png&name=orig"
$  wget -O small.jpg "https://pbs.twimg.com/media/AirUFB4CAAAvY4B?format=png&name=small"

$ identify small.jpg && identify orig.jpg 
small.jpg PNG 478x635 478x635+0+0 8-bit sRGB 455999B 0.000u 0:00.000
orig.jpg PNG 478x635 478x635+0+0 8-bit sRGB 455999B 0.000u 0:00.000
```

**Comment by CXwudi** [comment]
@mmpx12 I see, then I guess `format` parameter is not needed when using twitter-scraper

I don't think `name=small` would return same size as `name=orig` if the image is large enough, like https://pbs.twimg.com/media/FcPHriXagAAIfyM?format=jpg&name=small is much smaller than the one with `name=orig`

**Comment by mmpx12** [comment]
@CXwudi Small is like thumbnail. So i guess there is 3 size: name=small, nothing, and name=orig and it's only working with jpg files. But thx a lot for have pointing that 👍.
