### ISSUE TITLE
Why do I get "response status 404 Not Found:"? 

### ISSUE THREAD

**Issue by fablau** [mmpx12/twitter-media-downloader#24]
Just installed the standalone version for Linux, and when I run the following command:

`twmd -t 1713615721668784172`

I get this error:

`response status 404 Not Found: `

Any ideas?

**Comment by tmzg0000** [comment]
Is this API interface closed? The issue I have is the same as yours.

**Comment by fablau** [comment]
I am afraid this project has been kinda "abandoned." If so, anyone know any alternative?

**Comment by mmpx12** [comment]
@fablau its should work now with [v1.10.3](https://github.com/mmpx12/twitter-media-downloader/releases/tag/v1.10.3) ... if you still have the issue try to login (needed for nsfw).

**Comment by missuo** [comment]
> @fablau its should work now with [v1.10.3](https://github.com/mmpx12/twitter-media-downloader/releases/tag/v1.10.3) ... if you still have the issue try to login (needed for nsfw).

If you have enabled two-factor authentication and cannot log in, I can only try to use an account without two-factor authentication enabled. Unfortunately, I can only download one photo.

```bash
./twitter-media-downloader -a -U -L -u puppy_doll_88 -o /data/x -n 3000
```

**Comment by fablau** [comment]
Yes it works now! Thank you! I had to login though ;) Appreciated!

**Comment by fablau** [comment]
I am just wondering: is it possible to automate the login process without user interaction?

**Comment by missuo** [comment]
> I am just wondering: is it possible to automate the login process without user interaction?

Just log in when executing it for the first time.

**Comment by fablau** [comment]
Oh wow, I didn't know that... wonderful! Thank you so much!!

**Comment by fablau** [comment]
I am sorry to reopen this thread, but I didn't use twmd for over two days, and now it is asking for username and password again. I'd really need a way to automate it on the server backend to avoid any user interactions. How can I do that?

**Comment by fablau** [comment]
In the best-case scenario, it'd be nice to be able to specify username and password in the command itself, something like:

`twmd -L -u 'username' -pw 'password' -t 1713615721668784172`

**Comment by missuo** [comment]
> In the best-case scenario, it'd be nice to be able to specify username and password in the command itself, something like:
> 
> 
> 
> `twmd -L -u 'username' -pw 'password' -t 1713615721668784172`

This is not necessary, if you don't delete the cookies file, your login status doesn't disappear.

**Comment by fablau** [comment]
Well, I am not sure how cookies are used here since I am using the program through CLI, but no, I don't clear any cookies (how to do that on the CLI??). Fact is, after 15-20 minutes, twmd is asking for username and password again.

**Comment by missuo** [comment]
> Well, I am not sure how cookies are used here since I am using the program through CLI, but no, I don't clear any cookies (how to do that on the CLI??). Fact is, after 15-20 minutes, twmd is asking for username and password again.

After you enter your account password once, a cookies file is generated in the directory of the executable file. You do not need to do anything.

**Comment by fablau** [comment]
Oh, Ok... let me check because it is possible I have executed it from different locations...thanks for the info ;)

**Comment by fablau** [comment]
Yes, thank you so much, I was calling the script from another directory, hence the question again. Solved!
