### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by cubna-4** [mmpx12/twitter-media-downloader#29]
I can enter username but cannot enter password.

IF I don't use "-L", I could download all the images except the NSFW tweet without any problem, so it seems that the command is not wrong.

**Comment by mmpx12** [comment]
Which version and OS are you using? Its working fine for me

**Comment by cubna-4** [comment]
i using windows10, twmd v1.11.0-windows (i testing 386 and amd64  same thing happens in both version)

**Comment by cubna-4** [comment]
I am not sure, but I did a clean install the OS and it worked correctly.
