### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yesingyesing** [mmpx12/twitter-media-downloader#30]
i typed: twmd -u DragonPoker_aso -i
it says : Post "https://api.twitter.com/1.1/guest/activate.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by mmpx12** [comment]
Its look like a problem with https://github.com/n0madic/twitter-scraper ... I can't download anything too

**Comment by yesingyesing** [comment]
> Its look like a problem with https://github.com/n0madic/twitter-scraper ... I can't download anything too

do you have any idea that allows me to download all images from a twitter account now please? thank you!
