### ISSUE TITLE
I can not log in

### ISSUE THREAD

**Issue by 24ilain42** [mmpx12/twitter-media-downloader#34]
I try to log in using the [-L ], I can enter the username but not the password...
OS is windows 11and I tried twms 1.11.0~1.11.2

**Comment by mmpx12** [comment]
password will not print anything:

![login](https://github.com/mmpx12/twitter-media-downloader/assets/45767624/4d6d6ef2-e958-49dc-94ba-3198558a7947)

so just write your password and press enter, also the "logged in" is add by me for debug, it will not be print for you. 

If you try to logged in does twmd create twmd_cookies.json ?

**Comment by 24ilain42** [comment]
I tried it with another account and it worked!
