### ISSUE TITLE
Multiple images and videos downloaded are 0KB or incomplete

### ISSUE THREAD

**Issue by ubsn** [mmpx12/twitter-media-downloader#38]
I am writing to report a bug in the Twitter-media-downloader-v1.11.2-windows-amd64 software. When using the following command:

`twmd -u -L -a -o ./media -U`
multiple images and videos downloaded with this command are either 0KB in size or the data is not completely downloaded.

I appreciate your hard work in developing this software.
Thank you for your time and attention.

**Comment by mmpx12** [comment]
@ubsn  Is this still happen with the latest version (v1.12.0) and what is the user? you command aren't complete
