### ISSUE TITLE
Any request results in "response status 404 Not Found:"

### ISSUE THREAD

**Issue by Yozhylo** [mmpx12/twitter-media-downloader#41]
## How to reproduce:

Invoke the utility with any arguments.

## Environment

Tested on Windows 11, same results in both GUI & CLI v1.11.4 utility executables.

## Details

Calling the utility and specifying any tweet (both SFW & NSFW) results in 404.
The type of media therein doesn't matter.

**Comment by mmpx12** [comment]
@Yozhylo Can you specify the command with tweets you are trying to download ... But i know sometime tweets arent possible to download (dont know why).

**Comment by Yozhylo** [comment]
> @Yozhylo Can you specify the command with tweets you are trying to download ... But i know sometime tweets arent possible to download (dont know why).

Yes, of course.
```sh
$ twmd -B -v -t 1582505634506760192
$ twmd -t 156170319961391104
$ twmd -t 1765939515930063237
```

**Comment by mmpx12** [comment]
@Yozhylo its should work now with [version 1.12.0](https://github.com/mmpx12/twitter-media-downloader/releases/tag/v1.12.0).

But are you sure tweet  156170319961391104 exists ? (I cant get this one)

**Comment by Yozhylo** [comment]
> @Yozhylo its should work now with [version 1.12.0](https://github.com/mmpx12/twitter-media-downloader/releases/tag/v1.12.0).
> 
> But are you sure tweet 156170319961391104 exists ? (I cant get this one)

Will check if it does, and close the issue if true.
The forementioned tweet was taken from project's README.
