### ISSUE TITLE
How to login 

### ISSUE THREAD

**Issue by HakaVelli** [mmpx12/twitter-media-downloader#42]
How do i login?

I try -L|--login followed by my username and pass, but nothing happens.
Help please.

**Comment by mmpx12** [comment]
@HakaVelli you did something like `twmd -L user password -t <tweet_id>`?

login is interactive:

```
twmd -B  -L -t <tweet_id>
username: <username>
password: <password> #nothing will be print
Logged in # or Bad user/pass
```

**Comment by HakaVelli** [comment]
@mmpx12 no, i just typed -L|--login user pass

**Comment by mmpx12** [comment]
@HakaVelli just type -L with creds, you will then be promt to enter them.

**Comment by HakaVelli** [comment]
@mmpx12 Thanks for replying. I am stupid, so please could you write the exact command?

**Comment by mmpx12** [comment]
@HakaVelli `twmd -B  -L -t <tweet_id>`

**Comment by HakaVelli** [comment]
where in that comman is the username and pass?

**Comment by mmpx12** [comment]
just type: `twmd --no-banner --login --tweet <tweet_id>` and press enter then it will ask you for your creds

**Comment by mmpx12** [comment]
`twmd --no-banner --login -u babymatosa --all` => for pics and videos
`twmd --no-banner --login -u babymatosa --img` => for pics only
`twmd --no-banner --login -u babymatosa --video` => for video only
`twmd --no-banner --login -u babymatosa --all --retweet` => for pics, videos and retweet

But there is a readme and examples in the help message (-h or --help),  so please read them before asking

**Comment by HakaVelli** [comment]
@mmpx12 THANK YOU bro. Finally worked. Cant thank you enough!!!
