### ISSUE TITLE
Despite user/pw being correct, I always get error

### ISSUE THREAD

**Issue by fablau** [mmpx12/twitter-media-downloader#48]
I am apparently unable to log in. When I enter this commend:

 ```
twmd -L -B -s small -t 1783130850533535870
```

I am prompted to enter user and password. No matter how many times I enter them correctly, I always get "Bad user/pass"

I just installed your latest build for Linux. Thoughts?

**Comment by mmpx12** [comment]
Everything is working fine for me (v1.13.1 on archlinux) so make sure you dont have 2fa or you user/pass are correct (check on x.com) also try to delete twmd_cookies.json (check also for write  access)

**Comment by fablau** [comment]
Yes, it is working now... thank you for reminding me about permissions, I was actually calling the script from a non-writable directory. All good!
