### ISSUE TITLE
Can't login into account

### ISSUE THREAD

**Issue by RAZUMNO** [mmpx12/twitter-media-downloader#49]
When entering `-L|--login` I get asked about username and password. I can type the username into terminal, but I can't type the password for some reason. I'm using windows-amd64 1.13.1 version

**Comment by mmpx12** [comment]
@RAZUMNO Password will not be print ... Write it and press enter. Check https://github.com/mmpx12/twitter-media-downloader/issues/42 or https://github.com/mmpx12/twitter-media-downloader/issues/46

So just type your password and press enter.

**Comment by RAZUMNO** [comment]
Then for some reason I can't login into account even tho I'm typing the correct username and password. I checked by login in Twitter itself, but in the program I get `Bad user/pass`

**Comment by mmpx12** [comment]
Yes underscore is supported... Its working for me and im unable to repoduce this.

**Comment by RAZUMNO** [comment]
Is there a way to override hiding functionality so I can check maybe there is something when I'm typing password into cmd?

**Comment by RAZUMNO** [comment]
Found the issue. I'm using proxy file inside windows settings and the program didn't catch that for some reason.

**Comment by mmpx12** [comment]
While implement this ... But you can (copy) 
paste too

**Comment by mmpx12** [comment]
@RAZUMNO In v1.13.2 you can now use **-P** or **--login-plaintext**. Your password will be print.
