### ISSUE TITLE
Not works

### ISSUE THREAD

**Issue by thesuperankes** [mmpx12/twitter-media-downloader#60]
It does not work.

I downloaded the cli and tried to run it according to the commands in the repository usage section but it didn't work with any type of account, I tried to use the GUI and it didn't work either.

I ran it through virustotal and 3 antivirus report it as Trojan.

![image](https://github.com/mmpx12/twitter-media-downloader/assets/10577919/65b94bc4-c167-403f-8883-b4188720da8f)

**Comment by mmpx12** [comment]
Code is open source, so check by yourself, and you'll see this is false positive

**Comment by mmpx12** [comment]
Also its working:

![working](https://github.com/mmpx12/twitter-media-downloader/assets/45767624/6612b404-09b9-4259-9658-39cf0239c699)
